### ISSUE TITLE
Timeout for windows update patching is too low

### ISSUE THREAD

**Issue by perjahn** [perjahn/bender#2]
When using bender to install windows update patches, the tcp timeout is too low, the connection is often closed too early. It's both a timeout at the client (when using -batch to call the service) and at the server (windows service) that needs to be increased.

Maybe some other architecture could be implemented, that doesn't require a tcp connection to be open for an arbitrary long time? Polling from the client? Or some stateless protocol like REST?

**Comment by JohanLindvall** [comment]
Probably a job framework with REST status polling. Abandoned jobs with no status polls for x (30?) seconds would be cancelled automatically.

**Comment by perjahn** [comment]
As it was much easier to switch to Linux than spending time on workarounds for windows update, I'm closing this. Patches are truly welcome though!
